<?php


use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_form_alter().
 */
function proxima_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Check specifically for your node form ID
//   dump($form);die;
  if ($form_id == 'node_selection_form' || $form_id == 'node_selection_edit_form') {
    $form['title']['widget'][0]['value']['#required'] = FALSE;    // Attach the JS library
    $form['#attached']['library'][] = 'proxima/product_calculator';
    // Optional: Make the Total field Read-only via PHP as well
    // Note: Because it's an Inline Entity Form, deep targeting might be tricky in PHP,
    // but the JS will handle the visual calculation.
  }
  if ($form_id == 'node_commission_record_form' || $form_id == 'node_commission_record_edit_form') {
    $form['title']['#access'] = FALSE;
    $form['title']['widget'][0]['value']['#required'] = FALSE;
  }
}

function proxima_inline_entity_form_table_fields_alter(&$fields, $context) {
  // 1. Check if the parent is your "Selection" content type
  // 2. Check if the field is your "Product" field
  if ($context['parent_bundle'] == 'selection' && $context['field_name'] == 'field_product') {
    
    $fields['field_total'] = [
      'type' => 'field',
      'label' => t('Total'),
      'weight' => 10, // Adjust weight to move it to the end
      'display_options' => [
        'type' => 'number_decimal', // Optional: Ensure it formats as a number
        'settings' => [
           'scale' => 2,
        ],
      ],
    ];
  }
}



/**
 * Implements hook_ENTITY_TYPE_presave() for node entities.
 */
function proxima_node_presave(EntityInterface $entity) {

  // Get the client information field
  if ($entity->bundle() == 'selection') {
    if ($entity->hasField('field_client_information') && !$entity->get('field_client_information')->isEmpty()) {
      $client_info = $entity->get('field_client_information')->referencedEntities();
      
      if (!empty($client_info)) {
        $first_client = reset($client_info);
        $client_name = $first_client->label();
        
        // Set the title to client name if not already set or if it's a date fallback
        $entity->setTitle($client_name);
      }
    }
  }
  if ($entity->bundle() == 'commission_record') {
    if ($entity->hasField('field_architect_mistry_informati') && !$entity->get('field_architect_mistry_informati')->isEmpty()) {
      $client_info = $entity->get('field_architect_mistry_informati')->referencedEntities();
      
      if (!empty($client_info)) {
        $first_client = reset($client_info);
        $client_name = $first_client->label();
        
        $entity->setTitle($client_name);
      }
    }
  }
}


